SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

-- V10: Insert Colombia units of measure (15 base units)
INSERT INTO units_of_measure (uuid, name, abbreviation, enabled, created_at, updated_at)
VALUES
    (UUID_TO_BIN(UUID()), 'Unidad', 'UN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Caja', 'CJ', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Paquete', 'PQ', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Bulto', 'BL', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Kilogramo', 'KG', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Gramo', 'GR', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Tonelada', 'TON', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Litro', 'L', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Mililitro', 'ML', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Galón', 'GAL', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Metro', 'M', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Centímetro', 'CM', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Metro Cuadrado', 'M²', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Docena', 'DOC', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN(UUID()), 'Par', 'PAR', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    enabled = VALUES(enabled),
    updated_at = CURRENT_TIMESTAMP;
