package com.jcuadrado.erplitebackend.application.service.documenttype;

import com.jcuadrado.erplitebackend.application.port.in.documenttype.CreateDocumentTypeUseCase;
import com.jcuadrado.erplitebackend.application.port.out.DocumentTypePort;
import com.jcuadrado.erplitebackend.domain.documenttype.exception.DuplicateCodeException;
import com.jcuadrado.erplitebackend.domain.documenttype.model.DocumentType;
import com.jcuadrado.erplitebackend.domain.documenttype.service.DocumentTypeDomainService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Service implementing create document type use case.
 */
@Service
@RequiredArgsConstructor
@Transactional
public class CreateDocumentTypeService implements CreateDocumentTypeUseCase {
    
    private final DocumentTypePort documentTypePort;
    private final DocumentTypeDomainService domainService;
    
    @Override
    public DocumentType create(DocumentType documentType) {
        // Normalize code
        String normalizedCode = domainService.normalizeCode(documentType.getCode());
        documentType.setCode(normalizedCode);

        // Validate business rules
        domainService.validateCode(documentType.getCode());
        domainService.validateName(documentType.getName());
        
        // Check code uniqueness
        if (documentTypePort.existsByCode(documentType.getCode())) {
            throw new DuplicateCodeException(documentType.getCode());
        }
        
        // Set default values
        if (documentType.getActive() == null) {
            documentType.setActive(true);
        }
        
        // Save and return (UUID will be generated by database)
        return documentTypePort.save(documentType);
    }
}
